apiVersion: v2
name: observability-logs-aws-cloudwatch
description: A Helm chart for OpenChoreo Logs Module for AWS CloudWatch Logs
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - cloudwatch
  - aws
  - openchoreo
  - logs
maintainers:
  - name: OpenChoreo Team
home: https://github.com/openchoreo/community-modules
dependencies:
  - name: amazon-cloudwatch-observability
    version: 6.2.0
    repository: https://aws-observability.github.io/helm-charts
    condition: cloudWatchAgent.enabled
