# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.moesif.adapter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moesif-tracing-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: moesif-tracing-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moesif-tracing-adapter
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/adapter/configmap.yaml") . | sha256sum }}
      labels:
        app: moesif-tracing-adapter
    spec:
      securityContext:
        runAsUser: 10500
        runAsGroup: 10500
        runAsNonRoot: true
      containers:
      - name: moesif-tracing-adapter
        image: "{{ .Values.moesif.adapter.image.repository }}:{{ .Values.moesif.adapter.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.moesif.adapter.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 9100
        envFrom:
        - configMapRef:
            name: moesif-tracing-adapter
        volumeMounts:
        - name: moesif-search-secret
          mountPath: /etc/moesif/env
          readOnly: true
        resources:
          limits:
            cpu: {{ .Values.moesif.adapter.resources.limits.cpu }}
            memory: {{ .Values.moesif.adapter.resources.limits.memory }}
          requests:
            cpu: {{ .Values.moesif.adapter.resources.requests.cpu }}
            memory: {{ .Values.moesif.adapter.resources.requests.memory }}
      volumes:
      - name: moesif-search-secret
        secret:
          secretName: {{ .Values.moesif.adapter.searchSecretName }}
{{- end }}
