# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.moesif.adapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tracing-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: moesif-tracing-adapter
spec:
  type: ClusterIP
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: http
  selector:
    app: moesif-tracing-adapter
{{- end }}
