# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  namespace: {{ .Release.Namespace }}
data:
  relay: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      {{- range .Values.moesif.environments }}
      otlphttp/{{ . }}:
        endpoint: {{ $.Values.moesif.endpoint | default "https://api.moesif.net" | quote }}
        headers:
          {{- if eq $.Values.moesif.auth_mode "api-key" }}
          X-Api-Token: ${env:api_key}
          {{- else }}
          X-Moesif-Application-Id: ${env:{{ . | replace "-" "_" }}}
          {{- end }}
      {{- end }}

    connectors:
      routing:
        table:
          {{- range .Values.moesif.environments }}
          - context: resource
            statement: route() where resource.attributes["openchoreo.dev/environment"] == {{ . | quote }}
            pipelines: [ logs/{{ . }} ]
          {{- end }}

    processors:
      transform:
        log_statements:
          - context: resource
            statements:
              - set(attributes["service.name"], attributes["openchoreo.dev/component"])

    service:
      extensions: [health_check]
      pipelines:
        logs/in:
          receivers: [ otlp ]
          processors: [ transform ]
          exporters: [ routing ]

        {{- range .Values.moesif.environments }}
        logs/{{ . }}:
          receivers: [ routing ]
          exporters: [ otlphttp/{{ . }} ]
        {{- end }}
