apiVersion: v2
name: observability-logs-azure-loganalytics
description: A Helm chart for OpenChoreo Logs Module for Azure Log Analytics
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - azure
  - loganalytics
  - aks
  - openchoreo
  - logs
maintainers:
  - name: OpenChoreo Team
home: https://github.com/openchoreo/community-modules
