# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.dynatrace.credentials.create }}
{{- $c := .Values.dynatrace.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $c.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- with $c.ingestToken }}
  {{ $c.ingestTokenKey }}: {{ . | quote }}
  {{- end }}
  {{- with $c.platformToken }}
  {{ $c.platformTokenKey }}: {{ . | quote }}
  {{- end }}
  {{- with $c.oauthClientId }}
  {{ $c.oauthClientIdKey }}: {{ . | quote }}
  {{- end }}
  {{- with $c.oauthClientSecret }}
  {{ $c.oauthClientSecretKey }}: {{ . | quote }}
  {{- end }}
{{- end }}
